blank_issues_enabled: true
contact_links:
  - name: CARLA Garage
    url: https://github.com/autonomousvision/carla_garage/issues
    about: CARLA Garage issue tracker
  - name: Bench2Drive
    url: https://github.com/Thinklab-SJTU/Bench2Drive/issues
    about: Bench2Drive issue tracker
  - name: SimLingo
    url: https://github.com/RenzKa/simlingo/issues
    about: SimLingo issue tracker
  - name: Known issues
    url: https://ln2697.github.io/lead/docs/known_issues.html
    about: We track some well-known issues here
  - name: Frequent Asked Questions
    url: https://ln2697.github.io/lead/docs/faq.html
    about: Find answers to common questions
